### ISSUE TITLE
Aircraft causes FlightGear to crash upon startup

### ISSUE THREAD

**Issue by Marsdolphin** [5H1N0B11/Aircraft#85]
Mirage crashes upon startup for me, could not get through finalizing position
Reason unknown, possibly something dealing with the canvas image
MacBook MacOS Catalina with 8GB RAM and Intel Iris Plus Integrated Graphics

**Comment by Octal450** [comment]
You need to rename the folder to anything that isn't "Aircraft". I've been telling @5H1N0B11 to change it but it hasn't been done yet...

Josh

**Comment by Marsdolphin** [comment]
What I did was drag the Mirage-2000 folder out of "Aircraft" into the FGDATA Aircraft folder

**Comment by Marsdolphin** [comment]
And it still crashes in certain locations but in others it doesn't
